baseURL = "https://slides.joelvim.net"
languageCode = "en-us"
title = "Slides"
theme = "newsroom"
disableKinds = ["taxonomy", "taxonomyTerm", "RSS"]

[params]
  author = "Joël Vimenet"
  description = "Slides"
  message = ""
  hideAutoMenu = false
  [params.analytics.goatcounter]
    baseUrl = "https://goat.joelvim.net"


[permalinks]
presentations = "/:title"